### ISSUE TITLE
need APK file on command line?

### ISSUE THREAD

**Issue by Void48** [HarshalKudale/EasySideload-WSA#1]
![image](https://user-images.githubusercontent.com/85196642/138339395-bff7b09f-7d79-4e0e-b5a1-60b42efdfed5.png)

**Comment by HarshalKudale** [comment]
What are you trying to do?
Just drag and drop apk file on installer to install it.

Drag and drop any file to pushToDroid to copy it to downloads folder of WSA.

**Comment by HarshalKudale** [comment]
provide full screen shot
