### ISSUE TITLE
Spacing issue 

### ISSUE THREAD

**Issue by MaiSan9999** [HarshalKudale/EasySideload-WSA#13]
Spacing issue  Example C:/user/Mai San9999/ 
it will work with C:/user/Mai_San9999

**Comment by EaZyStudiio** [comment]
I'll send a Pull request soon to fix that

**Comment by EaZyStudiio** [comment]
![image](https://user-images.githubusercontent.com/55167211/156259353-1198a795-594b-4e82-a3cf-34d666a71c65.png)
Follow the image and download from that pull request that sould fix your issues

**Comment by MaiSan9999** [comment]
Thank You !
