### ISSUE TITLE
add -s 127.0.0.1:58526 to adb commands

### ISSUE THREAD

**Issue by badabing2005** [HarshalKudale/EasySideload-WSA#9]
It's best to add `-s 127.0.0.1:58526` to `adb push` and `adb install` commands to avoid the error
```
adb: error: failed to get feature set: more than one device/emulator
```
This of course can happen anytime an android device is connected to the PC

**Comment by sasabrahim** [comment]
assayer ca
`@echo off

cd /d %~dp0
adb connect 127.0.0.1:58526 
adb install %1 
adb push %1 ./storage/emulated/0/Download`

**Comment by sasabrahim** [comment]
sa marche
